import{i as c,S as u}from"./assets/vendor-9310f15c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const a={searchForm:document.querySelector(".search-form"),inputSearch:document.querySelector(".input-name"),btnSearch:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery")};a.searchForm.addEventListener("submit",n=>{n.preventDefault();const o=a.inputSearch.value;f(o)});const s={key:"41496485-2e747cbe724a23cc88d300532",image_type:"photo",orientation:"horizontal",safesearch:!0};function f(n){s.q=n;const o=new URLSearchParams(s);fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0){c.error({title:"Error",message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight",backgroundColor:"#EF4040"});return}m(e.hits),console.log(e),a.inputSearch.value=""}).catch(e=>console.log(e))}function m(n){const o=n.map(e=>`<li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img
          class="gallery-image"
          src="${e.webformatURL}"
          alt="${e.tags}"
          />
      </a>
    </li>`).join("");a.gallery.innerHTML="",a.gallery.insertAdjacentHTML("afterbegin",o),new u(".gallery a",{captionsData:"alt",captionDelay:250,captionsDataAlt:"image.tags"})}
//# sourceMappingURL=commonHelpers.js.map
